Documentation comments
tracer-protocol/perpetual-pools-contracts pull request #194
Opened 2021-11-05 02:31 UTC by sporejack

# Motivation
Various aspects of the codebase are currently lacking NatSpec-formatted doc comments or the quality of the existing ones is lacking (due to rapid changes, API modifications, etc.). The clarity of the codebase is paramount -- particularly with respect to auditing. This PR aims to remedy this.

# Changes
 - Add missing doc comments to `PoolCommitter`

# Acceptance Criteria
TBA

2021-11-17 06:05 UTC, mynameuhh requested changes

2021-11-17 06:12 UTC, Paul4912 commented on contracts/implementation/LeveragedPool.sol
> +     * @dev Only callable by governance
governor?

2021-11-17 06:15 UTC, Paul4912 approved these changes

2021-11-19 04:45 UTC, mynameuhh requested changes
This still has some natspec comments with [an extra whitespace line](https://github.com/tracer-protocol/perpetual-pools-contracts/pull/194/commits/9b3702d855a8308d6139fdd7865a8050047fba85#diff-6760f9a878a6c66a111cacdafd5a03599dfc1fb227ebc36ae7d133e4ab468f77R44) and [some without](https://github.com/tracer-protocol/perpetual-pools-contracts/pull/194/files#)

2021-11-22 05:18 UTC, mynameuhh approved these changes

2021-11-22 05:19 UTC, merged