Fee Transfer Tests
tracer-protocol/perpetual-pools-contracts pull request #195
Opened 2021-11-05 04:26 UTC by Paul4912

2021-11-15 05:04 UTC, mynameuhh commented
Can you please add a description to this? Preferably using the "Motivation + changes" format

2021-11-19 01:22 UTC, sporejack requested changes

2021-11-19 01:22 UTC, sporejack commented on test/LeveragedPool/transferFees.spec.ts
> +describe("LeveragedPool - feeTrasnfer", () => {
```suggestion
describe("LeveragedPool - feeTransfer", () => {
```

2021-11-19 01:22 UTC, sporejack commented on test/LeveragedPool/transferFees.spec.ts
> +    describe("Test Paused Pools cannot transfer tokens", async () => {
```suggestion
    context("Test Paused Pools cannot transfer tokens", async () => {
```

2021-11-19 01:32 UTC, mynameuhh requested changes
Generally we try to use a more behaviour oriented structure for test files, where we wrap tests of a related context in a `context` branch, with any number of `it`s for testing certain things within that functionality.

We as a team haven't really sat down and discussed exactly how we want our test suite to be laid out (something I will be adding to the backlog), but I would say the tests added here should be structured a bit more robustly so when we come around to refactoring it, we can reason about what is happening here a bit more easily.

2021-11-19 01:38 UTC, mynameuhh commented
> Generally we try to use a more behaviour oriented structure for test files, where we wrap tests of a related context in a `context` branch, with any number of `it`s for testing certain things within that functionality.
> 
> We as a team haven't really sat down and discussed exactly how we want our test suite to be laid out (something I will be adding to the backlog), but I would say the tests added here should be structured a bit more robustly so when we come around to refactoring it, we can reason about what is happening here a bit more easily.

I'll add that this is something I haven't done amazingly in the past but soon we'll have specifics and enforce them

2021-11-19 01:41 UTC, Paul4912 commented
> Generally we try to use a more behaviour oriented structure for test files, where we wrap tests of a related context in a `context` branch, with any number of `it`s for testing certain things within that functionality.
> 
> We as a team haven't really sat down and discussed exactly how we want our test suite to be laid out (something I will be adding to the backlog), but I would say the tests added here should be structured a bit more robustly so when we come around to refactoring it, we can reason about what is happening here a bit more easily.

I agree i try to wrap them in context where appropriate. But i think when there is like 1 or two that kind of fit in their own category i think theres no need to group them. I think we should apply groupings when there is enough to consider a group.

2021-11-19 01:46 UTC, Paul4912 commented
> > Generally we try to use a more behaviour oriented structure for test files, where we wrap tests of a related context in a `context` branch, with any number of `it`s for testing certain things within that functionality.
> > We as a team haven't really sat down and discussed exactly how we want our test suite to be laid out (something I will be adding to the backlog), but I would say the tests added here should be structured a bit more robustly so when we come around to refactoring it, we can reason about what is happening here a bit more easily.
> 
> I agree i try to wrap them in context where appropriate. But i think when there is like 1 or two that kind of fit in their own category i think theres no need to group them. I think we should apply groupings when there is enough to consider a group.

this one in particular i can group my two tests since they are happy path test cases.

2021-11-19 01:50 UTC, mynameuhh approved these changes

2021-11-19 04:05 UTC, sporejack approved these changes

2021-11-19 04:32 UTC, merged