SMA ramping
tracer-protocol/perpetual-pools-contracts pull request #300
Opened 2022-01-25 00:03 UTC by sporejack

# Issue
#299 

# Changes
 - Add `desiredPeriods` instance variable to `SMAOracle`
 - Add guard to `SMAOracle::update`
 - Add explanatory comment to `SMAOracle`

2022-01-26 23:52 UTC, sporejack commented
@mynameuhh Tests are failing due to one of the RV fixes not being present, which is unfortunate. My gut instinct is to disable the offending tests for now and then re-enable them when we do our coverage sweep?

2022-01-26 23:58 UTC, mynameuhh commented
@sporejack Yep that sounds good to me.

Make a ticket and chuck it in the "In scope v2" column just to make sure we don't forget

2022-01-27 00:57 UTC, mynameuhh requested changes

2022-01-27 00:57 UTC, mynameuhh commented on contracts/implementation/SMAOracle.sol
> +    uint256 desiredPeriods;
```suggestion
    uint256 immutable desiredPeriods;
```

2022-01-27 01:07 UTC, sporejack commented on contracts/implementation/SMAOracle.sol
> +    uint256 desiredPeriods;
Good call!

2022-01-27 01:20 UTC, mynameuhh approved these changes

2022-01-27 01:23 UTC, 0xhrithik approved these changes

2022-01-27 04:11 UTC, merged