Gas optimization
tracer-protocol/perpetual-pools-contracts pull request #414
Opened 2022-03-15 11:03 UTC by 0xhrithik

Applying relevant gas optimizations from [here](https://gist.github.com/hrkrshnn/ee8fabd532058307229d65dcd5836ddc)

2022-03-25 00:05 UTC, sporejack requested changes

2022-03-25 00:05 UTC, sporejack commented on contracts/implementation/AutoClaim.sol
>          uint256 nrUsers = users.length;
Why alias here? Unsure if it would reduce gas at all but it doesn't seem to add to clarity?

2022-03-25 00:05 UTC, sporejack commented on contracts/implementation/AutoClaim.sol
> +            return i + 1;
Not a change we need to make but a bit of a curio I suppose. I wonder if this yields *any* gas savings at all?

```suggestion
            return i++;
```

Somewhat doubtful off the top of my head given there's no dedicated increment instruction I don't think?

2022-03-28 09:41 UTC, 0xhrithik commented on contracts/implementation/AutoClaim.sol
> +            return i + 1;
roughly speaking this can save 30-40 gas per loop iteration. For lengthy loops, this can be significant

2022-03-28 09:41 UTC, 0xhrithik commented on contracts/implementation/AutoClaim.sol
>          uint256 nrUsers = users.length;
calldata array requires an extra calldataload operation (3 additional gas for each iteration except for the first).
this extra costs can be avoided by caching the array length

2022-03-30 06:57 UTC, sporejack commented on contracts/implementation/AutoClaim.sol
> +            return i + 1;
@0xhrithik I meant the increment vs addition.

2022-03-30 06:58 UTC, sporejack approved these changes

2022-03-30 08:08 UTC, merged