feat: updated IOracleWrapper interface to accommodate multiple oracles
tracer-protocol/perpetual-pools-contracts pull request #444
Opened 2022-03-31 14:17 UTC by doylio

## Changelog
- Updated `IOracleWrapper` interface to support multiple oracles
- Updated `ChainlinkOracleWrapper` and `SMAOracle` to match new interface
- Updated tests to match new interface

2022-04-01 00:08 UTC, sporejack requested changes
While it would be nice to rely on automatically generated getters for the actual oracle addresses themselves, I think we should enforce reversion on out of bounds access (which will probably necessitate writing the view manually).

```solidity
function oracles(uint256 offset) external view returns (address) {
    require(offset < numOracles, "SMA: Out of bounds");
}
```

2022-04-07 03:02 UTC, sporejack approved these changes

2022-04-11 03:18 UTC, CalabashSquash commented
Is this something we wanted for v2? It won't be audited before then.

2022-04-27 13:39 UTC, doylio commented
> Is this something we wanted for v2? It won't be audited before then.

@CalabashSquash I don't think I have the context around V2 & audits to understand this question, but it is something we want before Indices are deployed so that `IOracleWrapper` can be the same in both repos

2022-11-07 17:04 UTC, closed without merging