Set updateInterval if none is set
tracer-protocol/perpetual-pools-contracts pull request #460
Opened 2022-04-28 04:23 UTC by dospore

UpdateIntervalId does not get set on the totalCommit if there are no commits

Note investigating if there is a better place to put this.

2022-04-28 06:53 UTC, ScaredIbis approved these changes

2022-04-29 02:03 UTC, CalabashSquash requested changes

2022-04-29 02:03 UTC, CalabashSquash commented on contracts/implementation/PoolCommitter.sol
>       * @param longBalance The amount of settlement tokens in the long side of the pool
```suggestion
     * @param executionTracking A struct containing the update interval ID being executed, and the long and short total supplies
     * @param longBalance The amount of settlement tokens in the long side of the pool
```

2022-05-10 04:30 UTC, ScaredIbis commented
@CalabashSquash this has been running in testnet for a little while now and can confirm its working as expected. keen to get'er in if you're happy with it

2022-05-13 00:05 UTC, merged