Gas optimisations
tracer-protocol/perpetual-pools-contracts pull request #470
Opened 2022-05-05 23:41 UTC by CalabashSquash

Misc. gas ops

2022-05-06 02:17 UTC, iflp requested changes

2022-05-06 02:17 UTC, iflp commented on contracts/implementation/SMAOracle.sol
> -    using PRBMathSD59x18 for int256;
May want to delete the unused import

2022-05-06 03:15 UTC, CalabashSquash commented on contracts/implementation/SMAOracle.sol
> -    using PRBMathSD59x18 for int256;
Fixed

2022-05-06 03:46 UTC, iflp approved these changes

2022-05-06 03:55 UTC, sporejack approved these changes

2022-05-13 00:14 UTC, ScaredIbis approved these changes

2022-05-13 00:14 UTC, merged